teams_crest_dict = {
"Arsenal FC" : "https://crests.football-data.org/57.svg",
"Aston Villa FC" : "https://crests.football-data.org/58.svg",
"Blackburn Rovers FC" : "https://crests.football-data.org/59.svg",
"Bolton Wanderers FC" : "https://crests.football-data.org/60.svg",
"Chelsea FC" : "https://crests.football-data.org/61.svg",
"Everton FC" : "https://crests.football-data.org/62.svg",
"Fulham FC" : "https://crests.football-data.org/63.svg",
"Liverpool FC" : "https://crests.football-data.org/64.svg",
"Manchester City FC" : "https://crests.football-data.org/65.svg",
"Manchester United FC" : "https://crests.football-data.org/66.svg",
"Newcastle United FC" : "https://crests.football-data.org/67.svg",
"Norwich City FC" : "https://upload.wikimedia.org/wikipedia/en/8/8c/Norwich_City.svg",
"Queens Park Rangers FC" : "http://upload.wikimedia.org/wikipedia/de/d/d4/Queens_Park_Rangers.svg",
"Stoke City FC" : "http://upload.wikimedia.org/wikipedia/de/a/a3/Stoke_City.svg",
"Sunderland AFC" : "https://crests.football-data.org/71.svg",
"Tottenham Hotspur FC" : "https://crests.football-data.org/73.svg",
"West Bromwich Albion FC" : "https://crests.football-data.org/74.svg",
"Wigan Athletic FC" : "https://crests.football-data.org/75.svg",
"Wolverhampton Wanderers FC" : "https://crests.football-data.org/76.svg",
"Hull City AFC" : "https://crests.football-data.org/322.svg",
"Burnley FC" : "https://crests.football-data.org/328.svg",
"Birmingham City FC" : "https://crests.football-data.org/332.svg",
"Blackpool FC" : "https://crests.football-data.org/336.svg",
"Leicester City FC" : "https://crests.football-data.org/338.svg",
"Southampton FC" : "https://crests.football-data.org/340.svg",
"Leeds United FC" : "https://crests.football-data.org/341.svg",
"Derby County FC" : "https://crests.football-data.org/342.svg",
"Middlesbrough FC" : "https://crests.football-data.org/343.svg",
"Sheffield Wednesday FC" : "https://crests.football-data.org/345.svg",
"Watford FC" : "https://crests.football-data.org/346.svg",
"Charlton Athletic FC" : "https://crests.football-data.org/348.svg",
"Ipswich Town FC" : "https://crests.football-data.org/349.svg",
"Nottingham Forest FC" : "https://crests.football-data.org/351.svg",
"Crystal Palace FC" : "https://crests.football-data.org/354.svg",
"Reading FC" : "https://crests.football-data.org/355.svg",
"Sheffield United FC" : "https://crests.football-data.org/356.svg",
"Barnsley FC" : "https://crests.football-data.org/357.svg",
"Millwall FC" : "https://crests.football-data.org/384.svg",
"Rotherham United FC" : "https://crests.football-data.org/385.svg",
"Bristol City FC" : "https://crests.football-data.org/387.svg",
"Luton Town FC" : "https://crests.football-data.org/389.svg",
"Huddersfield Town AFC" : "https://crests.football-data.org/394.svg",
"Brighton & Hove Albion FC" : "https://crests.football-data.org/397.svg",
"Brentford FC" : "https://crests.football-data.org/402.svg",
"West Ham United FC" : "https://crests.football-data.org/563.svg",
"England" : "https://crests.football-data.org/770.svg",
"AFC Bournemouth" : "https://crests.football-data.org/1044.svg",
"Burton Albion FC" : "https://crests.football-data.org/1072.svg",
"Coventry City FC" : "https://crests.football-data.org/1076.svg",
"Peterborough United FC" : "https://crests.football-data.org/1077.svg",
"Preston North End FC" : "https://crests.football-data.org/1081.svg",
"Wycombe Wanderers FC" : "https://crests.football-data.org/1146.svg",
"FC Köln" : "https://crests.football-data.org/1.svg",
"TSG 1899 Hoffenheim" : "https://crests.football-data.org/2.svg",
"Bayer 04 Leverkusen" : "https://crests.football-data.org/3.svg",
"Borussia Dortmund" : "https://crests.football-data.org/4.svg",
"FC Bayern München" : "https://crests.football-data.org/5.svg",
"Hertha BSC" : "https://crests.football-data.org/9.svg",
"VfB Stuttgart" : "https://crests.football-data.org/10.svg",
"VfL Wolfsburg" : "https://crests.football-data.org/11.svg",
"FSV Mainz 05" : "https://crests.football-data.org/15.svg",
"FC Augsburg" : "https://crests.football-data.org/16.svg",
"SC Freiburg" : "https://crests.football-data.org/17.svg",
"Borussia Mönchengladbach" : "https://crests.football-data.org/18.svg",
"Eintracht Frankfurt" : "https://crests.football-data.org/19.svg",
"SpVgg Greuther Fürth 1903" : "https://crests.football-data.org/21.svg",
"FC Union Berlin" : "https://crests.football-data.org/28.svg",
"VfL Bochum 1848" : "https://crests.football-data.org/36.svg",
"Arminia Bielefeld" : "https://crests.football-data.org/38.svg",
"RB Leipzig" : "https://crests.football-data.org/721.svg",
}
