teams_crest_dict = {
    "Arsenal FC": "https://crests.football-data.org/57.svg",
    "Aston Villa FC": "https://crests.football-data.org/58.svg",
    "Blackburn Rovers FC": "https://crests.football-data.org/59.svg",
    "Bolton Wanderers FC": "https://crests.football-data.org/60.svg",
    "Chelsea FC": "https://crests.football-data.org/61.svg",
    "Everton FC": "https://crests.football-data.org/62.svg",
    "Fulham FC": "https://crests.football-data.org/63.svg",
    "Liverpool FC": "https://crests.football-data.org/64.svg",
    "Manchester City FC": "https://crests.football-data.org/65.svg",
    "Manchester United FC": "https://crests.football-data.org/66.svg",
    "Newcastle United FC": "https://crests.football-data.org/67.svg",
    "Norwich City FC": "https://upload.wikimedia.org/wikipedia/en/8/8c/Norwich_City.svg",
    "Queens Park Rangers FC": "http://upload.wikimedia.org/wikipedia/de/d/d4/Queens_Park_Rangers.svg",
    "Stoke City FC": "http://upload.wikimedia.org/wikipedia/de/a/a3/Stoke_City.svg",
    "Sunderland AFC": "https://crests.football-data.org/71.svg",
    "Tottenham Hotspur FC": "https://crests.football-data.org/73.svg",
    "West Bromwich Albion FC": "https://crests.football-data.org/74.svg",
    "Wigan Athletic FC": "https://crests.football-data.org/75.svg",
    "Wolverhampton Wanderers FC": "https://crests.football-data.org/76.svg",
    "Hull City AFC": "https://crests.football-data.org/322.svg",
    "Burnley FC": "https://crests.football-data.org/328.svg",
    "Birmingham City FC": "https://crests.football-data.org/332.svg",
    "Blackpool FC": "https://crests.football-data.org/336.svg",
    "Leicester City FC": "https://crests.football-data.org/338.svg",
    "Southampton FC": "https://crests.football-data.org/340.svg",
    "Leeds United FC": "https://crests.football-data.org/341.svg",
    "Derby County FC": "https://crests.football-data.org/342.svg",
    "Middlesbrough FC": "https://crests.football-data.org/343.svg",
    "Sheffield Wednesday FC": "https://crests.football-data.org/345.svg",
    "Watford FC": "https://crests.football-data.org/346.svg",
    "Charlton Athletic FC": "https://crests.football-data.org/348.svg",
    "Ipswich Town FC": "https://crests.football-data.org/349.svg",
    "Nottingham Forest FC": "https://crests.football-data.org/351.svg",
    "Crystal Palace FC": "https://crests.football-data.org/354.svg",
    "Reading FC": "https://crests.football-data.org/355.svg",
    "Sheffield United FC": "https://crests.football-data.org/356.svg",
    "Barnsley FC": "https://crests.football-data.org/357.svg",
    "Millwall FC": "https://crests.football-data.org/384.svg",
    "Rotherham United FC": "https://crests.football-data.org/385.svg",
    "Bristol City FC": "https://crests.football-data.org/387.svg",
    "Luton Town FC": "https://crests.football-data.org/389.svg",
    "Huddersfield Town AFC": "https://crests.football-data.org/394.svg",
    "Brighton & Hove Albion FC": "https://crests.football-data.org/397.svg",
    "Brentford FC": "https://crests.football-data.org/402.svg",
    "West Ham United FC": "https://crests.football-data.org/563.svg",
    "England": "https://crests.football-data.org/770.svg",
    "AFC Bournemouth": "https://crests.football-data.org/1044.svg",
    "Burton Albion FC": "https://crests.football-data.org/1072.svg",
    "Coventry City FC": "https://crests.football-data.org/1076.svg",
    "Peterborough United FC": "https://crests.football-data.org/1077.svg",
    "Preston North End FC": "https://crests.football-data.org/1081.svg",
    "Wycombe Wanderers FC": "https://crests.football-data.org/1146.svg",
    "FC Köln": "https://crests.football-data.org/1.svg",
    "TSG 1899 Hoffenheim": "https://crests.football-data.org/2.svg",
    "Bayer 04 Leverkusen": "https://crests.football-data.org/3.svg",
    "Borussia Dortmund": "https://crests.football-data.org/4.svg",
    "FC Bayern München": "https://crests.football-data.org/5.svg",
    "Hertha BSC": "https://crests.football-data.org/9.svg",
    "VfB Stuttgart": "https://crests.football-data.org/10.svg",
    "VfL Wolfsburg": "https://crests.football-data.org/11.svg",
    "FSV Mainz 05": "https://crests.football-data.org/15.svg",
    "FC Augsburg": "https://crests.football-data.org/16.svg",
    "SC Freiburg": "https://crests.football-data.org/17.svg",
    "Borussia Mönchengladbach": "https://crests.football-data.org/18.svg",
    "Eintracht Frankfurt": "https://crests.football-data.org/19.svg",
    "SpVgg Greuther Fürth 1903": "https://crests.football-data.org/21.svg",
    "FC Union Berlin": "https://crests.football-data.org/28.svg",
    "VfL Bochum 1848": "https://crests.football-data.org/36.svg",
    "Arminia Bielefeld": "https://crests.football-data.org/38.svg",
    "RB Leipzig": "https://crests.football-data.org/721.svg",
    "Barcelona": "https://media.api-sports.io/football/teams/529.png",
    "Atletico Madrid": "https://media.api-sports.io/football/teams/530.png",
    "Athletic Club": "https://media.api-sports.io/football/teams/531.png",
    "Valencia": "https://media.api-sports.io/football/teams/532.png",
    "Villarreal": "https://media.api-sports.io/football/teams/533.png",
    "Sevilla": "https://media.api-sports.io/football/teams/536.png",
    "Levante": "https://media.api-sports.io/football/teams/539.png",
    "Real Madrid": "https://media.api-sports.io/football/teams/541.png",
    "Alaves": "https://media.api-sports.io/football/teams/542.png",
    "Real Betis": "https://media.api-sports.io/football/teams/543.png",
    "Eibar": "https://media.api-sports.io/football/teams/545.png",
    "Getafe": "https://media.api-sports.io/football/teams/546.png",
    "Real Sociedad": "https://media.api-sports.io/football/teams/548.png",
    "Granada CF": "https://media.api-sports.io/football/teams/715.png",
    "Valladolid": "https://media.api-sports.io/football/teams/720.png",
    "Cadiz": "https://media.api-sports.io/football/teams/724.png",
    "Huesca": "https://media.api-sports.io/football/teams/726.png",
    "Celta Vigo": "https://media.api-sports.io/football/teams/538.png",
    "Osasuna": "https://media.api-sports.io/football/teams/727.png",
    "Elche": "https://media.api-sports.io/football/teams/797.png",
    "Angers": "https://media.api-sports.io/football/teams/77.png",
    "Bordeaux": "https://media.api-sports.io/football/teams/78.png",
    "Lille": "https://media.api-sports.io/football/teams/79.png",
    "Lyon": "https://media.api-sports.io/football/teams/80.png",
    "Marseille": "https://media.api-sports.io/football/teams/81.png",
    "Montpellier": "https://media.api-sports.io/football/teams/82.png",
    "Nantes": "https://media.api-sports.io/football/teams/83.png",
    "Nice": "https://media.api-sports.io/football/teams/84.png",
    "Paris Saint Germain": "https://media.api-sports.io/football/teams/85.png",
    "Dijon": "https://media.api-sports.io/football/teams/89.png",
    "Monaco": "https://media.api-sports.io/football/teams/91.png",
    "Nimes": "https://media.api-sports.io/football/teams/92.png",
    "Reims": "https://media.api-sports.io/football/teams/93.png",
    "Rennes": "https://media.api-sports.io/football/teams/94.png",
    "Strasbourg": "https://media.api-sports.io/football/teams/95.png",
    "Toulouse": "https://media.api-sports.io/football/teams/96.png",
    "Lorient": "https://media.api-sports.io/football/teams/97.png",
    "Stade Brestois 29": "https://media.api-sports.io/football/teams/106.png",
    "Metz": "https://media.api-sports.io/football/teams/112.png",
    "Lens": "https://media.api-sports.io/football/teams/116.png",
    "Saint Etienne": "https://media.api-sports.io/football/teams/1063.png",
    "Lazio": "https://media.api-sports.io/football/teams/487.png",
    "Sassuolo": "https://media.api-sports.io/football/teams/488.png",
    "AC Milan": "https://media.api-sports.io/football/teams/489.png",
    "Cagliari": "https://media.api-sports.io/football/teams/490.png",
    "Napoli": "https://media.api-sports.io/football/teams/492.png",
    "Udinese": "https://media.api-sports.io/football/teams/494.png",
    "Genoa": "https://media.api-sports.io/football/teams/495.png",
    "Juventus": "https://media.api-sports.io/football/teams/496.png",
    "AS Roma": "https://media.api-sports.io/football/teams/497.png",
    "Sampdoria": "https://media.api-sports.io/football/teams/498.png",
    "Atalanta": "https://media.api-sports.io/football/teams/499.png",
    "Bologna": "https://media.api-sports.io/football/teams/500.png",
    "Crotone": "https://media.api-sports.io/football/teams/501.png",
    "Fiorentina": "https://media.api-sports.io/football/teams/502.png",
    "Torino": "https://media.api-sports.io/football/teams/503.png",
    "Verona": "https://media.api-sports.io/football/teams/504.png",
    "Inter": "https://media.api-sports.io/football/teams/505.png",
    "Benevento": "https://media.api-sports.io/football/teams/506.png",
    "Spezia": "https://media.api-sports.io/football/teams/515.png",
    "Parma": "https://media.api-sports.io/football/teams/523.png",
    "PEC Zwolle": "https://media.api-sports.io/football/teams/193.png",
    "Ajax": "https://media.api-sports.io/football/teams/194.png",
    "Willem II": "https://media.api-sports.io/football/teams/195.png",
    "PSV Eindhoven": "https://media.api-sports.io/football/teams/197.png",
    "ADO Den Haag": "https://media.api-sports.io/football/teams/198.png",
    "De Graafschap": "https://media.api-sports.io/football/teams/199.png",
    "Vitesse": "https://media.api-sports.io/football/teams/200.png",
    "AZ Alkmaar": "https://media.api-sports.io/football/teams/201.png",
    "Groningen": "https://media.api-sports.io/football/teams/202.png",
    "NAC Breda": "https://media.api-sports.io/football/teams/203.png",
    "VVV Venlo": "https://media.api-sports.io/football/teams/204.png",
    "Fortuna Sittard": "https://media.api-sports.io/football/teams/205.png",
    "Heracles": "https://media.api-sports.io/football/teams/206.png",
    "Utrecht": "https://media.api-sports.io/football/teams/207.png",
    "Emmen": "https://media.api-sports.io/football/teams/208.png",
    "Feyenoord": "https://media.api-sports.io/football/teams/209.png",
    "Heerenveen": "https://media.api-sports.io/football/teams/210.png",
    "NEC Nijmegen": "https://media.api-sports.io/football/teams/413.png",
    "Roda": "https://media.api-sports.io/football/teams/414.png",
    "Twente": "https://media.api-sports.io/football/teams/415.png",
    "FC Volendam": "https://media.api-sports.io/football/teams/416.png",
    "Waalwijk": "https://media.api-sports.io/football/teams/417.png",
    "Almere City FC": "https://media.api-sports.io/football/teams/419.png",
    "Sparta Rotterdam": "https://media.api-sports.io/football/teams/426.png",
    "Bayern Munich": "https://media.api-sports.io/football/teams/157.png",
    "Hertha Berlin": "https://media.api-sports.io/football/teams/159.png",
    "SC Freiburg": "https://media.api-sports.io/football/teams/160.png",
    "VfL Wolfsburg": "https://media.api-sports.io/football/teams/161.png",
    "Werder Bremen": "https://media.api-sports.io/football/teams/162.png",
    "Borussia Monchengladbach": "https://media.api-sports.io/football/teams/163.png",
    "FSV Mainz 05": "https://media.api-sports.io/football/teams/164.png",
    "Borussia Dortmund": "https://media.api-sports.io/football/teams/165.png",
    "1899 Hoffenheim": "https://media.api-sports.io/football/teams/167.png",
    "Bayer Leverkusen": "https://media.api-sports.io/football/teams/168.png",
    "Eintracht Frankfurt": "https://media.api-sports.io/football/teams/169.png",
    "FC Augsburg": "https://media.api-sports.io/football/teams/170.png",
    "VfB Stuttgart": "https://media.api-sports.io/football/teams/172.png",
    "RB Leipzig": "https://media.api-sports.io/football/teams/173.png",
    "FC Schalke 04": "https://media.api-sports.io/football/teams/174.png",
    "Union Berlin": "https://media.api-sports.io/football/teams/182.png",
    "Arminia Bielefeld": "https://media.api-sports.io/football/teams/188.png",
    "Holstein Kiel": "https://media.api-sports.io/football/teams/191.png",
    "FC Koln": "https://media.api-sports.io/football/teams/192.png",
}
